/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mati' at '21/01/16 8:09' with Gradle 2.6
 *
 * @author mati, @date 21/01/16 8:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
